packages:
  - "applications/*"
  - "examples/*"
  - "libraries/*"
allowBuilds:
  '@swc/core': true
  unrs-resolver: true
publicHoistPattern:
  - "*changesets*"
  - "*commitlint*"
  - "*eslint*"
  - "*prettier*"
  - "*turbo*"
  - "*typescript*"
  - "*types*"
